updated according to changes in BuildTools

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -281,7 +281,7 @@ PACKAGE_BUGREPORT='http://projects.coin-or.org/BuildTools/newticket'
 
 ac_unique_file="solvers/asl.h"
 ac_default_prefix=`pwd`
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS ADDLIBS FADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE build build_cpu build_vendor build_os COIN_DEBUG_TRUE COIN_DEBUG_FALSE EGREP LN_S CDEFS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT ADD_CFLAGS MPICC INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE AMPLSOLVER_A MSVC_COMPILE_TRUE MSVC_COMPILE_FALSE ASLMAKEFLAGS ASLMAKEFILECMDS LIBEXT VPATH_DISTCLEANFILES LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS ADDLIBS FADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE build build_cpu build_vendor build_os EGREP LN_S CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT MPICC INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE AMPLSOLVER_A MSVC_COMPILE_TRUE MSVC_COMPILE_FALSE ASLMAKEFLAGS ASLMAKEFILECMDS LIBEXT VPATH_DISTCLEANFILES LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -726,6 +726,18 @@ ac_env_CDEFS_set=${CDEFS+set}
 ac_env_CDEFS_value=$CDEFS
 ac_cv_env_CDEFS_set=${CDEFS+set}
 ac_cv_env_CDEFS_value=$CDEFS
+ac_env_ADD_CFLAGS_set=${ADD_CFLAGS+set}
+ac_env_ADD_CFLAGS_value=$ADD_CFLAGS
+ac_cv_env_ADD_CFLAGS_set=${ADD_CFLAGS+set}
+ac_cv_env_ADD_CFLAGS_value=$ADD_CFLAGS
+ac_env_DBG_CFLAGS_set=${DBG_CFLAGS+set}
+ac_env_DBG_CFLAGS_value=$DBG_CFLAGS
+ac_cv_env_DBG_CFLAGS_set=${DBG_CFLAGS+set}
+ac_cv_env_DBG_CFLAGS_value=$DBG_CFLAGS
+ac_env_OPT_CFLAGS_set=${OPT_CFLAGS+set}
+ac_env_OPT_CFLAGS_value=$OPT_CFLAGS
+ac_cv_env_OPT_CFLAGS_set=${OPT_CFLAGS+set}
+ac_cv_env_OPT_CFLAGS_value=$OPT_CFLAGS
 ac_env_CC_set=${CC+set}
 ac_env_CC_value=$CC
 ac_cv_env_CC_set=${CC+set}
@@ -742,10 +754,6 @@ ac_env_CPPFLAGS_set=${CPPFLAGS+set}
 ac_env_CPPFLAGS_value=$CPPFLAGS
 ac_cv_env_CPPFLAGS_set=${CPPFLAGS+set}
 ac_cv_env_CPPFLAGS_value=$CPPFLAGS
-ac_env_ADD_CFLAGS_set=${ADD_CFLAGS+set}
-ac_env_ADD_CFLAGS_value=$ADD_CFLAGS
-ac_cv_env_ADD_CFLAGS_set=${ADD_CFLAGS+set}
-ac_cv_env_ADD_CFLAGS_value=$ADD_CFLAGS
 ac_env_MPICC_set=${MPICC+set}
 ac_env_MPICC_value=$MPICC
 ac_cv_env_MPICC_set=${MPICC+set}
@@ -834,21 +842,30 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
-  --enable-debug          compile with debug options and runtime tests
+  --enable-debug          compile all projects with debug options tests
+  --enable-debug-asl compile this project (ASL) with debug options
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
   --enable-maintainer-mode  enable make rules and dependencies not useful
 			  (and sometimes confusing) to the casual installer
 
+Optional Packages:
+  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
+  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-asl-verbosity specify the debug verbosity level for project ASL
+  --with-asl-checklevel specify the sanity check level for project ASL
+
 Some influential environment variables:
   CDEFS       Additional -D flags to be used when compiling C code.
+  ADD_CFLAGS  Additional C compiler options
+  DBG_CFLAGS  Debug C compiler options
+  OPT_CFLAGS  Optimize C compiler options
   CC          C compiler command
   CFLAGS      C compiler flags
   LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
               nonstandard directory <lib dir>
   CPPFLAGS    C/C++ preprocessor flags, e.g. -I<include dir> if you have
               headers in a nonstandard directory <include dir>
-  ADD_CFLAGS  Additional C compiler options
   MPICC       C MPI Compiler
   ASLMAKEFLAGS
               Compilation flags necessary for compiling the AMPL solver
@@ -1420,24 +1437,39 @@ echo $ECHO_N "checking whether we want to compile in debug mode... $ECHO_C" >&6
 if test "${enable_debug+set}" = set; then
   enableval="$enable_debug"
   case "${enableval}" in
-                   yes) coin_debug_compile=true
-
-cat >>confdefs.h <<\_ACEOF
-#define COIN_DEBUG 1
-_ACEOF
-
-                     enable_shared=no
-                     ;;
-                   no)  coin_debug_compile=false
-                     ;;
-                    *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-debug" >&5
+   yes) coin_debug_compile=true
+        enable_shared=no
+        ;;
+   no)  coin_debug_compile=false
+        ;;
+   *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-debug" >&5
 echo "$as_me: error: bad value ${enableval} for --enable-debug" >&2;}
    { (exit 1); exit 1; }; }
-                     ;;
-                 esac
+        ;;
+esac
 else
   coin_debug_compile=false
 fi;
+
+# Check whether --enable-debug-asl or --disable-debug-asl was given.
+if test "${enable_debug_asl+set}" = set; then
+  enableval="$enable_debug_asl"
+  case "${enableval}" in
+    yes) coin_debug_compile=true
+         enable_shared=no
+         ;;
+    no)  coin_debug_compile=false
+         ;;
+    *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-debug-asl" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-debug-asl" >&2;}
+   { (exit 1); exit 1; }; }
+         ;;
+ esac
+else
+  :
+fi;
+
+ # m4_ifvaln([ASL],
 
 if test $coin_debug_compile = true; then
   echo "$as_me:$LINENO: result: yes" >&5
@@ -1448,14 +1480,39 @@ echo "${ECHO_T}no" >&6
 fi
 
 
-
-if test "$coin_debug_compile" = true; then
-  COIN_DEBUG_TRUE=
-  COIN_DEBUG_FALSE='#'
+# Check whether --with-asl-verbosity or --without-asl-verbosity was given.
+if test "${with_asl_verbosity+set}" = set; then
+  withval="$with_asl_verbosity"
+  coin_asl_verbosity=$withval
 else
-  COIN_DEBUG_TRUE='#'
-  COIN_DEBUG_FALSE=
-fi
+  coin_asl_verbosity=0
+fi;
+
+cat >>confdefs.h <<_ACEOF
+#define COIN_ASL_VERBOSITY $coin_asl_verbosity
+_ACEOF
+
+
+
+# Check whether --with-asl-checklevel or --without-asl-checklevel was given.
+if test "${with_asl_checklevel+set}" = set; then
+  withval="$with_asl_checklevel"
+  coin_asl_checklevel=$withval
+else
+  coin_asl_checklevel=0
+fi;
+
+cat >>confdefs.h <<_ACEOF
+#define COIN_ASL_CHECKLEVEL $coin_asl_checklevel
+_ACEOF
+
+
+# We use the following variable to have a string with the upper case
+# version of the project name
+COIN_PRJCT=ASL
+
+
+ # m4_ifvaln([ASL],
 
 
 
@@ -1521,6 +1578,9 @@ fi
 
 
 
+
+
+
 coin_has_cc=yes
 
 save_cflags="$CFLAGS"
@@ -1528,12 +1588,12 @@ case $build in
   *-cygwin* | *-mingw*)
              comps="gcc cl" ;;
   *-linux-*) comps="xlc gcc cc pgcc icc" ;;
-  *)         comps="xlc cc gcc pgcc icc" ;;
+  *)         comps="xlc_r xlc cc gcc pgcc icc" ;;
 esac
 
 # We delete the cached value, since the test might not have been
 # performed with out choise of compilers earlier
-ac_cv_prog_CC=
+$as_unset ac_cv_prog_CC || test "${ac_cv_prog_CC+set}" != set || { ac_cv_prog_CC=; export ac_cv_prog_CC; }
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -2249,12 +2309,15 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 CFLAGS="$save_cflags"
 
-echo "$as_me:$LINENO: checking for C compiler options" >&5
-echo $ECHO_N "checking for C compiler options... $ECHO_C" >&6
-if test "${coin_cv_cflags+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test x"$CFLAGS" = x; then
+# Check if a project specific CFLAGS variable has been set
+if test x$COIN_PRJCT != x; then
+  eval coin_tmp=\${${COIN_PRJCT}_CFLAGS+set}
+  if test x$coin_tmp = xset; then
+    eval CFLAGS=\${${COIN_PRJCT}_CFLAGS}
+  fi
+fi
+
+if test x"$CFLAGS" = x; then
 
   coin_add_cflags=
   coin_opt_cflags=
@@ -2427,13 +2490,10 @@ rm -f conftest.err conftest.$ac_objext \
     coin_dbg_cflags="-g"
   fi
 
-  if test "$coin_debug_compile" = "true"; then
-    CFLAGS="$coin_dbg_cflags $coin_add_cflags $CDEFS $coin_warn_cflags"
-  else
-    if test -z "$coin_opt_cflags"; then
-      # Try if -O option works if nothing else is set
-      CFLAGS="-O"
-      cat >conftest.$ac_ext <<_ACEOF
+  if test -z "$coin_opt_cflags"; then
+    # Try if -O option works if nothing else is set
+    CFLAGS="-O"
+    cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
@@ -2478,8 +2538,30 @@ sed 's/^/| /' conftest.$ac_ext >&5
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-    fi
-    CFLAGS="$coin_opt_cflags $coin_add_cflags -DNDEBUG $CDEFS $coin_warn_cflags"
+  fi
+
+  if test x${DBG_CFLAGS+set} != xset; then
+    DBG_CFLAGS="$coin_dbg_cflags $coin_add_cflags $coin_warn_cflags"
+  fi
+  if test x${OPT_CFLAGS+set} != xset; then
+    OPT_CFLAGS="$coin_opt_cflags $coin_add_cflags -DNDEBUG $coin_warn_cflags"
+  fi
+
+  DBG_CFLAGS="$DBG_CFLAGS $ADD_CFLAGS $CDEFS"
+  OPT_CFLAGS="$OPT_CFLAGS $ADD_CFLAGS $CDEFS"
+
+  if test "$coin_debug_compile" = "true"; then
+    CFLAGS="$DBG_CFLAGS"
+  else
+    CFLAGS="$OPT_CFLAGS"
+  fi
+else
+  CFLAGS="$CFLAGS $ADD_CFLAGS $CDEFS"
+  if test x${DBG_CFLAGS+set} != xset; then
+    DBG_CFLAGS="$CFLAGS"
+  fi
+  if test x${OPT_CFLAGS+set} != xset; then
+    OPT_CFLAGS="$CFLAGS"
   fi
 fi
 
@@ -2490,6 +2572,7 @@ if test x"$ADD_CFLAGS" != x; then
 fi
 
 # Try if CFLAGS works
+save_CFLAGS="$CFLAGS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -2537,8 +2620,8 @@ fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
 if test -z "$CFLAGS"; then
-  { echo "$as_me:$LINENO: WARNING: The value CFLAGS=\"$CFLAGS\" do not work.  I will now just try '-O', but you might want to set CFLAGS manually." >&5
-echo "$as_me: WARNING: The value CFLAGS=\"$CFLAGS\" do not work.  I will now just try '-O', but you might want to set CFLAGS manually." >&2;}
+  { echo "$as_me:$LINENO: WARNING: The value CFLAGS=\"$save_CFLAGS\" do not work.  I will now just try '-O', but you might want to set CFLAGS manually." >&5
+echo "$as_me: WARNING: The value CFLAGS=\"$save_CFLAGS\" do not work.  I will now just try '-O', but you might want to set CFLAGS manually." >&2;}
   CFLAGS='-O'
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -2591,12 +2674,9 @@ rm -f conftest.err conftest.$ac_objext \
 echo "$as_me: WARNING: This value for CFLAGS does not work.  I will continue with empty CFLAGS, but you might want to set CFLAGS manually." >&2;}
   fi
 fi
-coin_cv_cflags="$CFLAGS"
 
-fi
-echo "$as_me:$LINENO: result: $coin_cv_cflags" >&5
-echo "${ECHO_T}$coin_cv_cflags" >&6 # AC_CACHE_CHECK([for C compiler options CXXFLAGS]
-CFLAGS="$coin_cv_cflags"
+{ echo "$as_me:$LINENO: C compiler options are: $CFLAGS" >&5
+echo "$as_me: C compiler options are: $CFLAGS" >&6;}
 
 
 if test x"$MPICC" = x; then :; else
@@ -3861,13 +3941,6 @@ echo "$as_me: error: conditional \"ALWAYS_FALSE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${COIN_DEBUG_TRUE}" && test -z "${COIN_DEBUG_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"COIN_DEBUG\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"COIN_DEBUG\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
 if test -z "${AMDEP_TRUE}" && test -z "${AMDEP_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"AMDEP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -4437,11 +4510,12 @@ s,@build@,$build,;t t
 s,@build_cpu@,$build_cpu,;t t
 s,@build_vendor@,$build_vendor,;t t
 s,@build_os@,$build_os,;t t
-s,@COIN_DEBUG_TRUE@,$COIN_DEBUG_TRUE,;t t
-s,@COIN_DEBUG_FALSE@,$COIN_DEBUG_FALSE,;t t
 s,@EGREP@,$EGREP,;t t
 s,@LN_S@,$LN_S,;t t
 s,@CDEFS@,$CDEFS,;t t
+s,@ADD_CFLAGS@,$ADD_CFLAGS,;t t
+s,@DBG_CFLAGS@,$DBG_CFLAGS,;t t
+s,@OPT_CFLAGS@,$OPT_CFLAGS,;t t
 s,@CC@,$CC,;t t
 s,@CFLAGS@,$CFLAGS,;t t
 s,@LDFLAGS@,$LDFLAGS,;t t
@@ -4449,7 +4523,6 @@ s,@CPPFLAGS@,$CPPFLAGS,;t t
 s,@ac_ct_CC@,$ac_ct_CC,;t t
 s,@EXEEXT@,$EXEEXT,;t t
 s,@OBJEXT@,$OBJEXT,;t t
-s,@ADD_CFLAGS@,$ADD_CFLAGS,;t t
 s,@MPICC@,$MPICC,;t t
 s,@INSTALL_PROGRAM@,$INSTALL_PROGRAM,;t t
 s,@INSTALL_SCRIPT@,$INSTALL_SCRIPT,;t t
